### ISSUE TITLE
Launching through Finder (MacOS) breaks Working Directory assumption

### ISSUE THREAD

**Issue by NoNoTeal** [khionu/CustomRichStatus#3]
**Describe the bug**
I wasn't sure how to open up the terminal file on Apple Darwin, which is mac(?) it ended up saying this as the error message

thread 'main' panicked at 'Config file not found. Please provide a `config.yml` file in the executable directory formatted as in the documentation', src/models/config.rs:30:26

there was a config.yml file but I'm assuming the files are not arranged in the correct way.

**To Reproduce**
1. Go to Releases on Chrome and download Apple-Darwin
2. Unzip the file and load the terminal file.
3. See error

**Expected behavior**
Not sure what happens after but maybe an application or the Rich Presence should work?

**Screenshots**
Just check Terminal after booting it up

**Environment (please complete the following information):**
 - OS: Mac OS Sierra v.10.12.6
 - Software version v1.10-86_64-apple-darwin

**Additional context**
No additional context supplied

**Comment by khionu** [comment]
I need to write up proper documentation, my apologies. Replace your `config.yml` with this file, make sure to rename it:
https://raw.githubusercontent.com/khionu/CustomRichStatus/master/config.defaults.yml

**Comment by NoNoTeal** [comment]
Ended up dropping this error message. 

thread 'main' panicked at 'Config file not found. Please provide a `config.yml` file in the executable directory formatted as in the documentation', src/models/config.rs:30:26

Also, this is what all the files look like from my side. https://imgur.com/a/tk0cGsy

**Comment by khionu** [comment]
So, the version that you have doesn't describe issues explicitly. There's some issue with opening that config file, is all it's able to say. Do you have it open in any other programs? Are you running the program from that directory?

**Comment by NoNoTeal** [comment]
I use TextEdit to edit the config.yml file, I pasted in the code you directed me to, but when I open up the custom_rich_status terminal window, it says the Config file can't be found. It's just that the terminal window can't find the folder src/models/config.rs in the folder itself. After the terminal says this message, it logs out.

**Comment by khionu** [comment]
`src/models/config.rs` won't exist in your directory. That's a source code file from before compilation. The error is on trying to open the `config.yml` file, explicitly.

Make sure you close TextEdit before running CustomRichStatus.

**Comment by NoNoTeal** [comment]
I closed TextEdit before running the terminal application, it still says the same error message.

**Comment by khionu** [comment]
Did you extract everything before running, or did you just run the program while it was in the zip?

**Comment by khionu** [comment]
Also, can you make sure the directory and all files in it aren't marked as Locked?

**Comment by khionu** [comment]
Someone got back to me with an explanation. When launching an executable through Finder, the working directory isn't the directory you're viewing, but your Home directory. Move the `config.yml` there, and try again

**Comment by NoNoTeal** [comment]
It said the preset was invalid after that

**Comment by khionu** [comment]
Well, that's progress. The next release I make will address this issue by the nature of some of the improvements I'm making, but for now, you should move the `presets` directory to your Home directory as well. The `LICENSE` and `README.md` files aren't used by the program, so that should be everything needed.

**Comment by khionu** [comment]
To summarize the issue, the program assumes the Working Directory (where the program is working from) is the same as the directory it exists in. This assumption is false when launched by Finder.

Until next release, the `presets` directory and the `config.yml` file need to be moved to the root of the Home Directory, which Finder sets as the Working Directory.

**Comment by NoNoTeal** [comment]
Alright, everything works fine now. https://imgur.com/a/rD6q2Tv

Some things that I should mention is that for the standard.yml file is that the " appear on the status as well, and it's also missing the small_image: and small_text: so I added that. I also removed the " for the images because the image will NOT show up if there are ""s

**Comment by NoNoTeal** [comment]
details: text
state: text
large_image: image_name
large_text: text
small_image: image_name
small_text: text

**Comment by khionu** [comment]
Glad it's working for you! And yes, the quotes are showing because that is part of YAML specification. Strings do not need quotes.

I'm reopening the issue as to make it more visible to people who may run into the same problem.
